
server:
  port: 8080

jwt:
  secret: hello.world.ee.ff.hello.world.ee.ff.hello.world.ee.ff

app:
  auth:
    tokenSecret: exampleTokenSecret
    tokenExpirationMsec: 3600000 #1시간 = 1,000 * 60 * 60 msc

  oauth2:
    authorizedRedirectUris:
      - http://example.com/redirect1
      - http://example.com/redirect2
      - http://example.com/redirect3


# DB Setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/traces_of_family
    username: manager
    password: _kTfpJuiM4P?-G0

  jpa:
    #프로젝트 실행시 자동으로 DDL(create, alter, drop) 을 생성할 것 인지 결정하는 설정
    #매번 테이블 생성을 새로 시도한다 / update: 변경이 필요한 경우 alter로 변경되고 테이블이 없는경우 create가 된다
    hibernate:
      ddl-auto: update #update
    #실제 JPA 구현체인 Hibernate가 동작하면서 발생하는 SQL을 포맷팅해서 출력한다 -> 실행되는 SQL의 가독성을 높여준다
    properties:
      hibernate:
        format_sql: true
    #처리시 발생하는 SQL을 보여줄 것인지 결정
    show-sql: true


